add support for capturing profiles.
testground/testground pull request #1209
Opened 2021-03-03 19:19 UTC by raulk

This PR introduces the ability to tell test plans to capture system profiles automatically.

For support on the Go SDK, check out this PR: https://github.com/testground/sdk-go/pull/38

There is now a new `profiles` field in `run` parameters, that can be set globally, or per-group:

```toml
[global]
  plan = "libp2p/ping"
  case = "ping"
  total_instances = 10
  builder = "docker:go"
  runner = "local:docker"

  [global.run]
  profiles = { cpu = "", heap = "5s", allocs = "10s" }
```

It takes a map of string => string, where the key is the profile type, and the value is the frequency (in Go `time.Duration` string representation, e.g. `5s`, `1m`).

For Go test plans:

* `cpu` => starts a CPU profile for the entire duration of the test job; the value is ignored.
* any other type listed in the godocs for the `runtime/pprof` package: https://golang.org/pkg/runtime/pprof/#Profile

The profiles will be written in the outputs directory, and will be available with `testground collect`.

![image](https://user-images.githubusercontent.com/1101242/109859874-5f6d6000-7c55-11eb-9688-cd576a8c5398.png)

2021-03-04 16:10 UTC, hacdias approved these changes

2021-03-04 16:12 UTC, hacdias requested changes
Please note that the composition tests are now failing:

```
=== RUN   TestDefaultTestParamsApplied
    TestDefaultTestParamsApplied: composition_test.go:102: 
        	Error Trace:	composition_test.go:102
        	Error:      	Not equal: 
        	            	expected: "value1:set"
        	            	actual  : "value1:default:composition"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-value1:set
        	            	+value1:default:composition
        	Test:       	TestDefaultTestParamsApplied
--- FAIL: TestDefaultTestParamsApplied (0.00s)
=== RUN   TestDefaultBuildParamsApplied
--- PASS: TestDefaultBuildParamsApplied (0.00s)
FAIL
FAIL	github.com/testground/testground/pkg/api	0.008s
```

2021-03-08 11:26 UTC, nonsense approved these changes

2021-03-08 11:29 UTC, nonsense commented
LGTM, solved the problem that @hacdias noticed, and will merge when the tests pass. Thanks @raulk and @hacdias !

2021-03-08 12:02 UTC, merged