Add go mod tidy to build stage for exec:go
testground/testground pull request #1469
Opened 2022-09-21 14:33 UTC by adlrocha

I was trying to run a composition that used different dependencies for the different instances using `exec:go`. I was setting the instances' dependencies in the `composition.toml` as follows: 
```toml
[[groups]]
  id = "attacker"
  [groups.build]

  [[groups.build.dependencies]]
       module = "github.com/filecoin-project/lotus"
       version = "8f48631fc48773821fd853b6d9612380b9d74cb4"
```
When running the composition I kept getting the error: `task cancelled due to error     {"err": "task of type run cancelled: unable to add replace directives to go.mod; exit status 1; output: "}`.

Inspecting the code, I realized that the `dependency.Target` had to be set explicitly for it to work with `exec:go`. Modifying the dependency for the instance in the `composition.toml` to the following made it work.
```toml
[[groups]]
  id = "attacker"
  [groups.build]

  [[groups.build.dependencies]]
       module = "github.com/filecoin-project/lotus"
       target = "github.com/filecoin-project/lotus"
       version = "8f48631fc48773821fd853b6d9612380b9d74cb4"
```
However, I was then getting an error when building the assets because after the dependency replacement, we needed a `go mod tidy`. Adding the small command included in this PR completely fixed the issue, and I was able to run the composition with multiple versions seamlessly.

2022-09-21 20:29 UTC, GlenDC approved these changes

2022-09-22 08:03 UTC, laurentsenta commented on pkg/build/exec_go.go
> +	cmd := exec.CommandContext(ctx, "go", append([]string{"mod", "tidy"})...)
```suggestion
	cmd := exec.CommandContext(ctx, "go", "mod", "tidy")
```

2022-09-22 08:12 UTC, laurentsenta commented
Thanks for the contribution @adlrocha and review @GlenDC,

A few notes:
- I'm looking into CI for your fork,
- If you don't mind I'll update this PR to fix the explicit `Target` issue and add an integration test,

2022-09-22 09:03 UTC, adlrocha commented
Sure, edit at will, let me know if you need anything from my side.

2022-10-03 12:46 UTC, laurentsenta approved these changes

2022-10-04 10:03 UTC, brdji requested changes
Looks good to me, but please add notes to the [changelog](https://github.com/testground/testground/blob/8b80d79fdb503dc7fb15135b73069ba2e487bfd9/CHANGELOG.md)

2022-10-05 12:54 UTC, laurentsenta commented
Updated with a CHANGELOG (since I took on finishing this PR) and merging,

Thanks for the contribution @adlrocha !

2022-10-05 12:54 UTC, merged